baseURL = "https://mi-ki-ri.github.io/hotta-tatsuya-official-2022/"
languageCode = "ja"
title = "HOTTA Tatsuya Official"
theme = "official-2022"
hasCJKLanguage = true

[taxonomies]
  tag = "tags"
  category = "categories"