baseURL = "https://mi-ki-ri.github.io/hotta-tatsuya-official-2022/"
languageCode = "en-us"
title = "HOTTA Tatsuya Official"
theme = "official-2022"
[taxonomies]
  tag = "tags"
  category = "categories"